// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDChr6QQ7ME3lBuwkqfmmJzkT8T3ZosVmw',
    appId: '1:1049831580990:android:a00c0fe26dc1455ada386f',
    messagingSenderId: '1049831580990',
    projectId: 'notperiod-5f395',
    storageBucket: 'notperiod-5f395.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqKN9HFrB-fx8JGqCZ_cti0css3eQvYf8',
    appId: '1:1049831580990:ios:0513ef27cfc6f039da386f',
    messagingSenderId: '1049831580990',
    projectId: 'notperiod-5f395',
    storageBucket: 'notperiod-5f395.appspot.com',
    androidClientId: '1049831580990-32andqqeebl276csr8j4v6jqgrcuaf7a.apps.googleusercontent.com',
    iosClientId: '1049831580990-n3hefe97vf3is0858vsb407l2u9fnvvd.apps.googleusercontent.com',
    iosBundleId: 'com.example.internship',
  );
}
